Remove unnecessary log output
test-fullautomation/robotframework-testsuitesmanagement pull request #161
Opened 2023-05-12 07:37 UTC by namsonx

2023-05-12 13:50 UTC, test-fullautomation requested changes
Hi Son,
Thank you for your pull-request.

I'm a bit confused.
What is the issue for this change?

check passed must be displayed if a min- or maximum version is provided and we pass the check.

check passed mustn't be displayed if both, min- and maximum version are not provided.

Should be like
```
if (self.sMinVersion.strip() != '' or self.sMaxVersion.strip() != '') and bVersionCheck:
   logger.info(.....)
```
Thank you,
 Thomas

2023-05-12 16:04 UTC, HolQue commented on RobotFramework_TestsuitesManagement/Config/CConfig.py
> -        if bVersionCheck:
Now `bVersionCheck` is set, but not used. This makes no sense.
Nevertheless: You removed a mandatory message. Why? A result of an executed version check has to be logged.

2023-05-12 16:04 UTC, HolQue requested changes
See my code comments ...

2023-05-17 07:12 UTC, namsonx commented
Hello Thomas and Holger,

Sorry, it's my mistake! I misunderstood while reading the ticket #140 
I will provide new commit for this pull-request.

Thank you,
Son

2023-05-17 14:37 UTC, test-fullautomation approved these changes
Hi Son,
looks good to me now!
Thank you,
 Thomas

2023-05-17 14:58 UTC, merged