Htv3hc/feat/trigger other workflow
test-fullautomation/robotframework-testsuitesmanagement pull request #228
Opened 2023-09-27 07:35 UTC by huavanthong

Hi Thomas,

I would like to update code to trigger the build of RobotFramework AIO at this repos following behavior below:
* A new-pull-request, or updated-pull-request coming request to **develop** branch in this repos will trigger **trigger-build-aio** and **status-build-aio**. 
```yaml 
  pull_request:
    types:
      - closed
      - opened
      - synchronize
    branches: 
      - develop
```
* **trigger-build-aio** job will use [Webhook ](https://docs.github.com/en/webhooks/about-webhooks-for-repositories) feature to send a curl POST to **test-fullautomation/RobotFramework_AIO**, and trigger pipeline on it. And it also sends info related to merge request branch and the current repository to request it
```
curl -X POST https://api.github.com/repos/test-fullautomation/RobotFramework_AIO/dispatches \
          --header 'authorization: Bearer ${{ secrets.PAT_THONG }}' \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          --data '{"event_type": "Triggered by other workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "branch": "'"$PULL_REQUEST_BRANCH"'" }}'
```
* **status-build-aio** job will wait the status of RobotFramework_AIO pipeline until it completely, and get the result of pipeline.
If the status is FAIL, we can the result on this pipeline.

Could you help me review this pull-request? 

Thank you and best regards,
Thong Hua

2023-09-29 07:27 UTC, ngoan1608 commented
Hi Thong,

I think it should be better that this feature is implemented in a new workflow (separated `*.yml` file).
So that it is easy for us to update, maintain and avoid side-effect.

Thank you,
Ngoan

2023-09-29 07:30 UTC, ngoan1608 requested changes

2023-09-29 07:30 UTC, ngoan1608 commented on .github/workflows/release_to_pypi.yml
> +  trigger-build-aio:
The trigger job is also executed when tagging for releasing PyPI. 
It is not expected.

2023-09-29 08:07 UTC, huavanthong commented
Hi Ngoan,

Thank you for your comments. I have updated it. 
Please take it for your info.

Best regards,
Thong Hua

2023-10-02 11:44 UTC, test-fullautomation approved these changes
Hi Thong,
thank you for your pull-request.
I will merge it immediately once we released 0.9.0.
Thank you,
 Thomas

2023-10-23 11:25 UTC, merged

2023-10-23 11:25 UTC, test-fullautomation commented
Hi @huavanthong ,
I will need this change for all repositories, correct?
Thank you,
 Thomas