Update log output of testsuite management
test-fullautomation/robotframework-testsuitesmanagement pull request #99
Opened 2023-02-08 08:47 UTC by namsonx

2023-02-08 12:06 UTC, HolQue requested changes
Please consider also:
(1)
I would prefer to have all logged paths encapsulated in single quotes (like also done at other positions).

Why have you changed from `f"..."` to `f'...'`?

2023-02-08 15:35 UTC, test-fullautomation commented
:-)

Hi Son,
in general we put since TML all dynamic parts of logged data in single quotes.

E.g.
```print(f"My dynamic data: '{myData}'"```

This helps to separate the text from the displayed data.
It also helps to see e.g. wrong spaces, ... in the dynamic data.
So, please change your strings back to double quotes and set the dynamic parts in single quotes.

This is a general design rule for all output data for screen as well as log files.

Thank you,
 Thomas

2023-02-08 15:35 UTC, test-fullautomation approved these changes
Hi Son,
please read my findings.
Thank you,
 Thomas

2023-02-09 13:47 UTC, test-fullautomation approved these changes
Hi Son,
looks good to me!
Thank you,
 Thomas

2023-02-09 13:47 UTC, test-fullautomation commented on RobotFramework_TestsuitesManagement/Keywords/CSetup.py
> +        logger.info(f"Suite Path: '{RobotFramework_TestsuitesManagement.CTestsuitesCfg.oConfig.sTestcasePath}'")
Perfect!

2023-02-09 13:48 UTC, merged